# Generated by Django 4.2.15 on 2024-08-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="포트폴리오 제목"),
                ),
                (
                    "logotype",
                    models.CharField(
                        max_length=100, verbose_name="포트폴리오 로고 종류"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="portfolio", verbose_name="포트폴리오 썸네일 이미지"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 날짜"),
                ),
            ],
        ),
    ]
