# Generated by Django 4.2.15 on 2024-08-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="고객 이름"),
                ),
                ("phone", models.CharField(max_length=100, verbose_name="고객 번호")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="고객 이메일"),
                ),
                (
                    "brand_name",
                    models.CharField(max_length=100, verbose_name="브랜드 이름"),
                ),
                ("brand_mean", models.TextField(verbose_name="브랜드 의미")),
                ("brand_desc", models.TextField(verbose_name="브랜드 묘사")),
                ("brand_target", models.TextField(verbose_name="고객 타겟층")),
                (
                    "logo_type",
                    models.CharField(max_length=100, verbose_name="로고 종류"),
                ),
                (
                    "brand_image",
                    models.TextField(max_length=300, verbose_name="넣고 싶은 이미지"),
                ),
                (
                    "brand_color",
                    models.CharField(max_length=300, verbose_name="원하는 싶은 색상"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 날짜"),
                ),
            ],
        ),
    ]
