# Generated by Django 4.2.15 on 2024-08-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo_design_app', '0003_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=100, verbose_name='고객 번호'),
            preserve_default=False,
        ),
    ]
