# Generated by Django 4.2.15 on 2024-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo_design_app', '0006_portfolio_survey_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='칼럼 제목')),
                ('content', models.TextField(verbose_name='칼럼 컨텐츠')),
                ('thumbnail', models.ImageField(upload_to='column', verbose_name='칼럼 썸네일 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='칼럼 작성 날짜')),
            ],
        ),
    ]
