# Generated by Django 4.2.15 on 2024-08-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logo_design_app", "0007_column"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Portfolio",
        ),
    ]
