# Generated by Django 4.2.15 on 2024-08-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="칼럼 제목")),
                ("content", models.TextField(verbose_name="칼럼 컨텐츠")),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="column", verbose_name="칼럼 썸네일 이미지"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="칼럼 작성 날짜"
                    ),
                ),
            ],
        ),
    ]
